apiVersion: v2
name: nginx-deployment
description: Nginx deployment for ns1
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: nginx
    version: "0.1.0"
    repository: "file://../../charts/nginx/0.1.0"
