name: Deploy Helm Chart

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Chart version to deploy'
        required: true
        type: string
      namespace:
        description: 'Kubernetes namespace for deployment'
        required: true
        type: string
      replicaCount:
        description: 'Number of replicas'
        required: true
        type: string
        default: '1'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
      NAMESPACE: ${{ github.event.inputs.namespace }}
      REPLICAS: ${{ github.event.inputs.replicaCount }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug options
        run: |
          echo "Starting deployment workflow simulation ..."
          echo "Now deploying chart version ${VERSION} to namespace ${NAMESPACE} with replicaset ${REPLICAS}..."

